export enum ActionTypes {

    ADD_USER = "ADD_USER",
    REMOVE_USER = "REMOVE_USER",
    LOGOUT = "LOGOUT",
    REFRESH = "REFRESH",
    ADD_NEXT_USER = "ADD_NEXT_USER",
    ADD_MESSAGE = "ADD_MESSAGE",
    ADD_CHAT = "ADD_CHAT",
    ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE",
    ADD_SOCKET = "ADD_SOCKET",
    ADD_ONLINE_USERS = "ADD_ONLINE_USERS",
}