const Enums={
    MESSAGE:"MESSAGE",
    NOTIFICATION:"NOTIFICATION",
    JOIN:"JOIN",
    LEAVE:"LEAVE",
    DISCONNECT:"DISCONNECT",
    SEND_MESSAGE:"SEND_MESSAGE",
    SEND_NOTIFICATION:"SEND_NOTIFICATION",
    SEND_ONLINE_USERS:"SEND_ONLINE_USERS",
    FOLLOW_TYPE:"FOLLOW",
    COMMENT_TYPE:"COMMENT",
    LIKE_TYPE:"LIKE",
    FOLLOW_BACK:"FOLLOW_BACK",
}
module.exports = Enums;